services:
  # PostgreSQL database
  db:
    image: postgres:16-alpine
    container_name: twitter_clone_db_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitter_user -d twitter_clone"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - twitter_network

  # Backend API with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: twitter_clone_backend_dev
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_MINUTES=${JWT_EXPIRY_MINUTES}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
      - /app/Properties
    restart: unless-stopped
    networks:
      - twitter_network

  # Frontend with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: twitter_clone_frontend_dev
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
    networks:
      - twitter_network

volumes:
  postgres_data:
    driver: local

networks:
  twitter_network:
    driver: bridge